test-description = This is a test description.

company-none-description = You have no allegiance to any organization, or are making an effort to hide it. Regardless, not associating with an organization has its benefits.

gas-new-galactic-description = The state of Gas New Galactic (GNG) was created by Roland Esau, brother of the former CEO of the SIC. Though at first a corporate entity, “Gas New Galactic Industries” corporation established a large mining colony on the border of rogue space that proved to be a riling success. The colonial surge to one of the last surviving plasma worlds in the rogue sector on the edge of space granted substantial sway in the New Galactic Congress’ space, leading to their official recognition as a sovereign entity. GNG itself does not hold elections, and is ruled by an elite class of executives. As their name and origins imply, the GNG’s most profound exports are that of plasma, tritium, and heavy tanker vessels. Their primary trade partners are other members of the NGC.

armadan-exiles-description = A miscellaneous group of individuals whom have been forcibly displaced-by or exiled-from Armadan space. Few of these exiles may speak Comm-Nac, but most speak common. Regardless of each individuals origins, all of the exiles share a common hatred for military intervention and totalitarian authority. Their tenets are as follows, Avoid serving in any and all positions of leadership. Support any other, even at one's own expense. Money is no object. All members have a voice, so long as their message intends to prolong and protect the lives of others. Act on your own accord, wander freely, and take responsibility upon committing wrongdoing.

union-j-description = A group of hard working men and women who make and break things; contractually neutral but often favours the NGC and law enforcement affairs in practice. There is only one requirement to be an official member: A member’s name must start with or sound like “John”. All official members are given living stipends and benefits, whereas all other “non-members” are given the privilege to work for Union J., which has otherwise provided itself upon being an organization built on honest labour.
unionj-name-prefix = John {$baseName}

cerceakan-description = The Cerceakan Reaches, Expanse, or Yards, are an extension of the governmental body of Cerceakan within the Null Sector that is no less deeply religious than their origins. Despite their grounded home territory; the C1R are not present in the Lark Region to govern, but to learn and develop in the name of their homeworld. C1R provide rudimentary throwaway research vessels to the Null's inhabitants in return for freedom to spread the faith of Circi, and the freedom to conduct their own research in the region.

ursidine-description = A collective based on a distant remote zone of space, the enigmatic Ursidine Collective are a race of Dwarvish clones. The Ursidine Collective's Exploration (UCE) branch of their Ethno-State seeks new frontiers away from their homeworld, sending vessels ships to all corners of the Null. Most aligned to the Dwarvish species of the galaxy, the UCE is conducting outreach in the Lark Region.

nexwealth-description = Though nobody knows when the NexWealth Consortium formed, it's universally agreed that when the beginnings of Rogue-Null interstellar trade began, they were already there. Born from Rogue Financiers, the NWC grew into an enigmatic cartel of smuggling, takeovers and illicit deals. Their people are called "agents", who wear black suits and blank expressions leading to frequent confusions between the NWC and the Armada. Operating in luxurious vessels, their agents are known for being cold and relentless. Despite their organization being a criminal one, the NWC has a reputation for flawless transactions, and a brutal internal order held together by a stringent, almost Armadan discipline. Even Their motto carries a mystique: "Fortune favors the discreet."