using System.Linq;
using Content.Client._Null.Nullith.BUI;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._Null.Nullith;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Null.Nullith.UI;

[GenerateTypedNameReferences]
public sealed partial class NullithConsoleMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    public event Action<ButtonEventArgs>? OnOrderApproved;
    private readonly NullithConsoleBoundUserInterface _menu;
    private readonly List<PoICategory> _categoriesAsStrings = [];
    private PoICategory? _category;

    private List<string> _lastAvailableProtos = [];
    private List<string> _lastUnavailableProtos = [];
    private bool _freeListings = false;
    private bool _validId = false;

    public NullithConsoleMenu(NullithConsoleBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _menu = owner;
        Title = Loc.GetString("nullith-console-menu-title");
        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
    }

    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateLocations(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateLocations(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoriesAsStrings[id];
        Categories.SelectId(id);
    }

    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateLocations(List<string> availablePrototypes,
        List<string> unavailablePrototypes,
        bool free,
        bool canPurchase)
    {
        PoIList.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = GetPoIPrototypesFromIds(availablePrototypes);
        AddPoIsToControls(newVessels, search, free, canPurchase);

        var newUnavailableVessels = GetPoIPrototypesFromIds(unavailablePrototypes);
        AddPoIsToControls(newUnavailableVessels, search, free, false);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, ordered by name.
    /// </summary>
    private List<BuyablePoIPrototype?> GetPoIPrototypesFromIds(IEnumerable<string> protoIds)
    {
        var vesselList = protoIds
            .Select(it => _protoManager.TryIndex<BuyablePoIPrototype>(it, out var proto) ? proto : null)
            .Where(it => it != null)
            .ToList();

        vesselList.Sort((x, y) =>
            string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase));
        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as PoIRows in the UI.
    /// </summary>
    private void AddPoIsToControls(IEnumerable<BuyablePoIPrototype?> vessels,
        string search,
        bool free,
        bool canPurchase)
    {
        foreach (var prototype in vessels)
        {
            // Filter any ships
            if (prototype == null)
                continue;
            if (_category != null && !prototype.PoICategories.Contains(_category.Value))
                continue;
            if (search.Length > 0 && !prototype.Name.Contains(search, StringComparison.InvariantCultureIgnoreCase))
                continue;

            var priceText = free
                ? Loc.GetString("shipyard-console-menu-listing-free")
                : BankSystemExtensions.ToSpesoString(prototype.Price);

            var poIRowEntry = new PoIRow
            {
                PoI = prototype,
                VesselName = { Text = prototype.Name },
                Purchase = { Text = Loc.GetString("shipyard-console-purchase-available"), Disabled = !canPurchase },
                Guidebook =
                {
                    Disabled = prototype.GuidebookPage is null, TooltipDelay = 0.2f, ToolTip = prototype.Description
                },
                Price = { Text = priceText },
            };
            poIRowEntry.Purchase.OnPressed += args => { OnOrderApproved?.Invoke(args); };
            PoIList.AddChild(poIRowEntry);
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _categoriesAsStrings.Clear();
        Categories.Clear();

        // Use (un)available prototypes in combination to get all category listings.
        AddCategoriesFromPrototypes(availablePrototypes.Concat(unavailablePrototypes).Distinct());

        _categoriesAsStrings.Sort();

        // Add "All" category at the top of the list
        _categoriesAsStrings.Insert(0, PoICategory.All);

        foreach (var str in _categoriesAsStrings)
        {
            Categories.AddItem(Loc.GetString($"nullith-console-class-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<BuyablePoIPrototype>(protoId, out var prototype))
                continue;

            foreach (var category in prototype.PoICategories)
            {
                if (!_categoriesAsStrings.Contains(category) && category != PoICategory.All)
                {
                    _categoriesAsStrings.Add(category);
                }
            }
        }
    }

    public void UpdateState(NullithConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);

        //ShipAppraisalLabel.Text = $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)";
        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        // TODO: Doesnt exist. Remove this later.// TODO: Doesnt exist. Remove this later.
        //DeedTitle.Text = state.ShipDeedTitle ?? $"None";
        _freeListings = state.FreeListings;
        _validId = state.IsTargetIdPresent;
        PopulateLocations(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }
}
