using Content.Client._Null.Nullith.BUI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Null.Nullith.UI;

[GenerateTypedNameReferences]
internal sealed partial class NullithRulesPopup : FancyWindow
{
    private readonly NullithConsoleBoundUserInterface _menu;

    public NullithRulesPopup(NullithConsoleBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        _menu = owner;
        Title = Loc.GetString("shipyard-console-menu-title");
        AcceptButton.OnPressed += OnRulesAccept;
    }

    private void OnRulesAccept(BaseButton.ButtonEventArgs args)
    {
        Close();
    }
}
