using System.Runtime.CompilerServices;
using Content.Client.Guidebook;
using Content.Shared._Null.Nullith;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Null.Nullith.UI;

[GenerateTypedNameReferences]
public sealed partial class PoIRow : PanelContainer
{
    [Robust.Shared.IoC.Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly GuidebookSystem _guidebook = default!;
    public BuyablePoIPrototype? PoI;
    public PoIRow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _guidebook = _entitySystem.GetEntitySystem<GuidebookSystem>();

        Guidebook.OnPressed += LoadVesselGuidebook;
    }

    [MethodImpl(MethodImplOptions.NoOptimization)]
    private void LoadVesselGuidebook(BaseButton.ButtonEventArgs args)
    {
        if (PoI?.GuidebookPage == null)
            return;

        var guidebookEntries = new List<ProtoId<GuideEntryPrototype>> { PoI.GuidebookPage.Value };
        _guidebook.OpenHelp(guidebookEntries);
    }
}
